version: '2.2'
services:
      
  elastic1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elastic1
    environment:
      - node.name=elastic1
      - discovery.seed_hosts=elastic2
      - cluster.initial_master_nodes=elastic1,elastic2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elastic
      
  elastic2:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: elastic2
    environment:
      - node.name=elastic2
      - discovery.seed_hosts=elastic1
      - cluster.initial_master_nodes=elastic1,elastic2
      - cluster.name=ELK_Cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    container_name: kibana1
    environment:
      SERVER_NAME: gdlm12845.americas.ad.flextronics.com
      ELASTICSEARCH_HOSTS: http://localhost:9200
    ports:
      - "5601:5601"
    volumes:
      - esdata03:/usr/share/elasticsearch/data
    networks:
      - elastic

volumes:
  esdata01:
    driver: local
  esdata02:
    driver: local
  esdata03:
    driver: local

networks:
  elastic:
    driver: bridge
